name: super_simple_accountant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+12

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  crypto: ^3.0.6
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  flutter_launcher_icons: ^0.14.1
  firebase_messaging: ^15.0.3
  in_app_review: ^2.0.9
  flutter_localizations:
    sdk: flutter
  riverpod_annotation: ^2.3.5
  pdf: ^3.11.1
  path_provider: ^2.1.4
  share_plus: ^10.1.1
  html: ^0.15.4
  universal_html: ^2.2.4
  fl_chart: ^0.69.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  lottie: ^3.2.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  flutter_speed_dial: ^7.0.0
  cloud_functions: ^5.3.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.0
  sign_in_with_apple: ^6.1.4
  flutter_svg: ^2.0.17
  purchases_flutter: ^8.4.0
  purchases_ui_flutter: ^8.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_channel_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/animations/
    - environment/