name: super_simple_accountant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^15.0.3
  in_app_review: ^2.0.9
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/