name: super_simple_accountant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^15.0.3
  in_app_review: ^2.0.9
  flutter_localizations:
    sdk: flutter
  riverpod_annotation: ^2.3.5
  pdf: ^3.11.1
  path_provider: ^2.1.4
  share_plus: ^10.1.1
  html: ^0.15.4
  universal_html: ^2.2.4
  fl_chart: ^0.69.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/