// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYpz2B18J9jhZfqm8bAvkCoGNnfr3gFxo',
    appId: '1:955905474794:android:21ebaca9dd5e97bc4c1793',
    messagingSenderId: '955905474794',
    projectId: 'super-simple-accountant',
    storageBucket: 'super-simple-accountant.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfO5Vl1HwiW5KAWPq4vuXuml0tHdT_TOQ',
    appId: '1:955905474794:web:a43358c3c0844a7b4c1793',
    messagingSenderId: '955905474794',
    projectId: 'super-simple-accountant',
    authDomain: 'super-simple-accountant.firebaseapp.com',
    storageBucket: 'super-simple-accountant.appspot.com',
    measurementId: 'G-50T2BYMJ7F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBlSjtlBkBmfvWUefiApC7jXiAFIZPUqc',
    appId: '1:955905474794:ios:6a548d6da1bb105e4c1793',
    messagingSenderId: '955905474794',
    projectId: 'super-simple-accountant',
    storageBucket: 'super-simple-accountant.appspot.com',
    iosBundleId: 'app.simpleaccountant.ios',
  );

}